#!name=Apple WLOC 定位修改
#!desc=修改 Apple 网络定位返回坐标 (Shadowrocket 小火箭)
#!author=Yu9191 Rewrite
#!homepage=https://github.com/Yu9191/wloc
#!icon=https://raw.githubusercontent.com/Yu9191/wloc/refs/heads/main/wloc.jpg
#!category=Tools
#!wloc-script-sha256=wloc.js:a2bac6c2b9ee2766ba3cb6090293ae6c05c92448ad65f9882a8071b4ee743a72
#!wloc-script-sha256=wloc-settings.js:0f58214589a7fbe5cd31d32b6c554984b601493648561b1f8d46e6b02c866130

[Script]
Apple WLOC = type=http-response,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=https://raw.githubusercontent.com/wTechArtist/location/696a4ced72c232a21304023c4b29f077a01d27ed/dist/wloc.js,argument=longitude=113.94114&latitude=22.544577&accuracy=25&logLevel=info
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://raw.githubusercontent.com/wTechArtist/location/696a4ced72c232a21304023c4b29f077a01d27ed/dist/wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com
