#!name=Apple WLOC 定位修改
#!desc=修改 Apple 网络定位返回坐标 (Shadowrocket 小火箭)
#!author=Yu9191 Rewrite
#!homepage=https://github.com/Yu9191/wloc
#!icon=https://raw.githubusercontent.com/Yu9191/wloc/refs/heads/main/wloc.jpg
#!category=Tools
#!wloc-script-sha256=wloc.js:79aa0ee1329b29c4bbda8d4d7a10f0b9122f9f63e63abf6f0eac67fa12f77a99
#!wloc-script-sha256=wloc-settings.js:02f7b2bc348135309d8ddcbba56b56e588a4ffaea6cae7a8cbd93e8cb684f33a

[Script]
Apple WLOC = type=http-response,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=https://raw.githubusercontent.com/wTechArtist/location/696a4ced72c232a21304023c4b29f077a01d27ed/dist/wloc.js,argument=longitude=113.94114&latitude=22.544577&accuracy=25&logLevel=info
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://raw.githubusercontent.com/wTechArtist/location/696a4ced72c232a21304023c4b29f077a01d27ed/dist/wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com
